image: google/cloud-sdk:alpine

variables:
  ENV_API_NAME: "fastapi-service"
  ENV_ST_NAME: "streamlit-service"
  IMAGE_NAME_FS: "fastapi-app"
  IMAGE_NAME_ST: "streamlit-app"
  ARTIFACT_REPO: "bankprediction"
  REGION: "europe-north1"
  GOOGLE_PROJECT_ID: "$projectname"  # проект GCP

stages:
  - deploy

# Этап для развертывания FastAPI
deploy_fastapi:
  stage: deploy
  script:
    - cp $jsonkey12 /tmp/service-acct.json  # Аутентификация
    - gcloud auth activate-service-account --key-file=/tmp/service-acct.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    # Развертываем FastAPI сервис
    - gcloud run deploy "$ENV_API_NAME" \
        --image="${REGION}-docker.pkg.dev/$GOOGLE_PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME_FS:latest" \
        --region="$REGION" \
        --platform="managed" \
        --allow-unauthenticated \
        --set-env-vars="APP_ENV=production"
  only:
    - main

# Этап для развертывания Streamlit
deploy_streamlit:
  stage: deploy
  script:
    - cp $jsonkey12 /tmp/service-acct.json  # Аутентификация
    - gcloud auth activate-service-account --key-file=/tmp/service-acct.json
    - gcloud config set project $GOOGLE_PROJECT_ID
    # Получаем URL FastAPI для передачи в Streamlit
    - FASTAPI_URL=$(gcloud run services describe "$ENV_API_NAME" --region="$REGION" --format='value(status.url)')
    # Развертываем Streamlit сервис и передаем URL FastAPI как переменную окружения
    - gcloud run deploy "$ENV_ST_NAME" \
        --image="${REGION}-docker.pkg.dev/$GOOGLE_PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME_ST:latest" \
        --region="$REGION" \
        --platform="managed" \
        --allow-unauthenticated \
        --set-env-vars="FASTAPI_URL=$FASTAPI_URL"
  only:
    - main
