image: google/cloud-sdk:alpine

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - main
  script:
    - echo $jsonkey12 #Used for auth.
    - cp $jsonkey12 /tmp/serivce-acct.json #Used for auth.
    - gcloud auth activate-service-account --key-file=/tmp/service-acct.json
    - gcloud config set project $projectname # for project ID
    - gcloud builds submit  --config=cloudbuild.yaml --substitutions=_PROJECT_ID=$projectname,_ARTIFACT_REPO=$ARTIFACT_REPO,_ENV_API_NAME=$ENV_API_NAME,\
      ENV_ST_NAME=$ENV_ST_NAME,_ENV=$ENV,_SERVICE_NAME=$SERVICE_NAME .
  variables:
    ENV_API_NAME: "api"
    ENV_ST_NAME: "streamlit"
    IMAGE_NAME_FS: "fastapi"
    IMAGE_NAME_ST: "streamlit"
    ARTIFACT_REPO: "bankprediction"
    SERVICE_NAME: "api"
