steps:
  # build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_FS:$_ENV"
        
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API/streamlit",
        "-t",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_ST:$_ENV"

      ]
    # push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_FS:$_ENV"
      ]
  # push Streamlit container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_ST:$_ENV"
      ]
  # deploy FastAPI to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME", # имя сервиса FastAPI
        "--image",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_FS:$_ENV",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8004"
      ]
  # deploy Streamlit to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME_ST", # имя сервиса Streamlit
        "--image",
        "us-central1-c-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$IMAGE_NAME_ST:$_ENV",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8501"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
