steps:
  # build the image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
        
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API/streamlit",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"

      ]
    # push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  # push Streamlit container image for deployment
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]
      
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "$_IMAGE_NAME_FS",
        "--member",
        "allUsers",
        "--region",
        "europe-north1",
        "--role",
        "roles/run.invoker",
         "--impersonate-service-account",
      "cicd-56@inspired-bebop-436018-t4.iam.gserviceaccount.com"
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "$_IMAGE_NAME_ST",
        "--member",
        "allUsers",
        "--region",
        "europe-north1",
        "--role",
        "roles/run.invoker",
        "--impersonate-service-account",
      "cicd-56@inspired-bebop-436018-t4.iam.gserviceaccount.com"
      ]  
  # deploy FastAPI to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_IMAGE_NAME_FS", # FastAPI name service
        "--image",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000"
      ]
  # deploy Streamlit to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_IMAGE_NAME_ST", #  Streamlit name service
        "--image",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8501"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
