steps:
  # Build and push FastAPI container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME"
      ]

  # Deploy FastAPI to Cloud Run and get the URL 
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-fastapi"
    args:
      [
        "run",
        "deploy",
        "$_IMAGE_NAME_FS",
        "--image",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_FS:$_ENV_API_NAME",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8000"
      ]
    # Capture the URL of the deployed FastAPI service
    #name: "gcr.io/cloud-builders/gcloud"
    #id: "get-fastapi-url"
    #entrypoint: "bash"
    #args:
      #[
        #"-c",
        #"export _FASTAPI_URL=$(gcloud run services describe $_IMAGE_NAME_FS --region europe-north1 --format 'value(status.url)') && echo _FASTAPI_URL=$_FASTAPI_URL"
      #]

  # - name: "gcr.io/cloud-builders/gcloud"
  #   id: "get-fastapi-url"
  #   entrypoint: "bash"
  #   args:
  #     [
  #       "-c",
  #       "export _FASTAPI_URL=$(gcloud run services describe $_IMAGE_NAME_FS --region europe-north1 --format 'value(status.url)')"
  #     ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "API/streamlit",
        "-t",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME"
      ]

  #Deploy Streamlit to Cloud Run, with the FastAPI URL as an environment variable 
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_IMAGE_NAME_ST",
        "--image",
        "us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "8501",
        "--set-env-vars",
        "FASTAPI_URL=${(gcloud run services describe $_IMAGE_NAME_FS --region europe-north1 --format 'value(status.url)')}" # Set FastAPI URL as an environment variable
      ]
  # - name: "gcr.io/cloud-builders/gcloud"
  #   id: "deploy-streamlit"
  #   entrypoint: "bash"
  #   args:
  #     [
  #       "-c",
  #       "_FASTAPI_URL=$(gcloud run services describe $_IMAGE_NAME_FS --region europe-north1 --format 'value(status.url)') && gcloud run deploy $_IMAGE_NAME_ST --image us-central1-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REPO/$_IMAGE_NAME_ST:$_ENV_ST_NAME --region europe-north1 --platform managed --allow-unauthenticated --port 8501 --set-env-vars FASTAPI_URL=$_FASTAPI_URL"
  #     ]
options:
  logging: CLOUD_LOGGING_ONLY