version: '3.9'
services:
  spark:
    build: .
    ports:
      - "8079:19888"
    volumes:
      - /c/Users/Timur/DataspellProjects/Bankprediction/train.csv:/opt/spark/work-dir/files/train.csv
      - /home/liontim94/mlruns:/app/mlruns

  mlflow:
    build:
        context: .
        dockerfile: mlflow/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /home/liontim94/mlruns:/app/mlruns
      - /home/liontim94/mlflow_models:/app/mlflow_models








