image: google/cloud-sdk:alpine

deploy_staging:
  stage: deploy
  environment: staging
  only:
    - main
  script:
    - cp $jsonkey /tmp/serivce-acct.json #Used for auth.
    - gcloud auth activate-service-account --key-file=/tmp/service-acct.json
    - gcloud config set project $projectname # for project ID
    - gcloud builds submit  --config=cloudbuild.yaml --substitutions=_PROJECT_ID=$projectname,_ARTIFACT_REPO=$ARTIFACT_REPO,_ENV_IMG_NAME=$ENV_IMG_NAME,_ENV=$ENV,_SERVICE_NAME=$SERVICE_NAME .
  variables:
    ENV_IMG_NAME: "api"
    ENV: "bankprediction"
    ARTIFACT_REPO: "bankprediction"
    SERVICE_NAME: "api"
