version: '3.8'
services:
  mlflow:
    build: .
    ports:
      - "8095:19888"
    volumes:
      #- /c/Users/Timur/DataspellProjects/Bankprediction/train.csv:/opt/spark/work-dir/files/train.csv
      - /home/liontim94/mlruns:/app/mlruns

